Name:           ros-kinetic-roscpp
Version:        1.12.0
Release:        0%{?dist}
Summary:        ROS roscpp package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/roscpp
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-cpp-common >= 0.3.17
Requires:       ros-kinetic-message-runtime
Requires:       ros-kinetic-rosconsole
Requires:       ros-kinetic-roscpp-serialization
Requires:       ros-kinetic-roscpp-traits >= 0.3.17
Requires:       ros-kinetic-rosgraph-msgs >= 1.10.3
Requires:       ros-kinetic-rostime
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-xmlrpcpp
BuildRequires:  pkgconfig
BuildRequires:  ros-kinetic-catkin >= 0.5.78
BuildRequires:  ros-kinetic-cpp-common >= 0.3.17
BuildRequires:  ros-kinetic-message-generation
BuildRequires:  ros-kinetic-rosconsole
BuildRequires:  ros-kinetic-roscpp-serialization
BuildRequires:  ros-kinetic-roscpp-traits >= 0.3.17
BuildRequires:  ros-kinetic-rosgraph-msgs >= 1.10.3
BuildRequires:  ros-kinetic-roslang
BuildRequires:  ros-kinetic-rostime
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-xmlrpcpp

%description
roscpp is a C++ implementation of ROS. It provides a client library that enables
C++ programmers to quickly interface with ROS Topics, Services, and Parameters.
roscpp is the most widely used ROS client library and is designed to be the
high-performance library for ROS.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Mar 18 2016 Dirk Thomas <dthomas@osrfoundation.org> - 1.12.0-0
- Autogenerated by Bloom

* Fri Mar 11 2016 Dirk Thomas <dthomas@osrfoundation.org> - 1.11.17-0
- Autogenerated by Bloom

